services:
  blooddonation.apis:
    build:
      context: .
      dockerfile: BloodDonation.Apis/Dockerfile
    image: blooddonation.apis
    ports:
      - "5152:8080"
      - "7165:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: blood_donation
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
      
    
  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"
  
volumes:
  pgdata:
    
